services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment: ["TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"]
    networks: [rplace-net]

  valkey:
    image: valkey/valkey:latest
    command: valkey-server --port 6379 --requirepass ${VALKEY_PASSWORD} --appendonly yes --appendfsync everysec --save 900 1 --save 300 10 --save 60 10000 --io-threads ${IO_THREADS} --maxmemory ${VALKEY_MAX_MEMORY} --maxmemory-policy allkeys-lru
    volumes:
      - valkey-data:/data
    restart: always
    ports:
      - "6380:6379"
    networks:
      - rplace-net
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${VALKEY_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

#  insight:
#    image: redis/redisinsight:latest
#    container_name: valkey_gui
#    ports:
#      - "5540:5540"
#    restart: always
#    depends_on:
#      valkey:
#        condition: service_healthy
#    networks:
#      - rplace-net
#    volumes:
#      - insight-storage:/data

  rplace-app:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "9090:9090"
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${PORT}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - VALKEY_HOST=valkey:6380
      - X_MAX=${X_MAX}
      - Y_MAX=${Y_MAX}
      - IO_THREADS=${IO_THREADS}
      - VALKEY_MAX_MEMORY=${VALKEY_MAX_MEMORY}
      - MASTER_API_KEY=${MASTER_API_KEY}
      - VITE_API_URL=${VITE_API_URl}
    depends_on:
      valkey:
        condition: service_healthy
    networks:
      - rplace-net
    restart: always

volumes:
  valkey-data:
    driver: local
  #insight-storage:
    #driver: local

networks:
  rplace-net:
    driver: bridge
